/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bus {
  'id' : string,
  'status' : BusStatus,
  'driverID' : string,
  'busType' : string,
  'busNumber' : string,
  'speed' : number,
  'routeId' : string,
  'currentStopIndex' : bigint,
  'conductorID' : string,
}
export type BusStatus = { 'OnTime' : null } |
  { 'Cancelled' : null } |
  { 'Delayed' : null };
export interface BusTiming {
  'id' : string,
  'arrivalTime' : Time,
  'departureTime' : Time,
  'routeId' : string,
  'busId' : string,
}
export type PaymentMethod = { 'Cash' : null } |
  { 'Online' : null };
export interface Route {
  'id' : string,
  'name' : string,
  'toStop' : string,
  'stops' : Array<string>,
  'fromStop' : string,
}
export interface Ticket {
  'id' : string,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'timingId' : string,
  'ticketId' : string,
  'passengerName' : string,
  'toStop' : string,
  'fromStop' : string,
  'busId' : string,
  'amount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addBus' : ActorMethod<
    [string, string, string, string, string, string, BusStatus],
    undefined
  >,
  'addBusTiming' : ActorMethod<[string, string, Time, Time, string], undefined>,
  'addRoute' : ActorMethod<
    [string, string, string, string, Array<string>],
    undefined
  >,
  'bookTicket' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      PaymentMethod,
      bigint,
    ],
    undefined
  >,
  'getAllBuses' : ActorMethod<[], Array<Bus>>,
  'getAllRoutes' : ActorMethod<[], Array<Route>>,
  'getBusDetails' : ActorMethod<[string], Bus>,
  'getBusesByRouteId' : ActorMethod<[string], Array<Bus>>,
  'getTicket' : ActorMethod<[string], Ticket>,
  'getTimingsByRouteId' : ActorMethod<[string], Array<BusTiming>>,
  'updateBusPosition' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];