/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusStatus = IDL.Variant({
  'OnTime' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Delayed' : IDL.Null,
});
export const Time = IDL.Int;
export const PaymentMethod = IDL.Variant({
  'Cash' : IDL.Null,
  'Online' : IDL.Null,
});
export const Bus = IDL.Record({
  'id' : IDL.Text,
  'status' : BusStatus,
  'driverID' : IDL.Text,
  'busType' : IDL.Text,
  'busNumber' : IDL.Text,
  'speed' : IDL.Float64,
  'routeId' : IDL.Text,
  'currentStopIndex' : IDL.Nat,
  'conductorID' : IDL.Text,
});
export const Route = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'toStop' : IDL.Text,
  'stops' : IDL.Vec(IDL.Text),
  'fromStop' : IDL.Text,
});
export const Ticket = IDL.Record({
  'id' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'timingId' : IDL.Text,
  'ticketId' : IDL.Text,
  'passengerName' : IDL.Text,
  'toStop' : IDL.Text,
  'fromStop' : IDL.Text,
  'busId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const BusTiming = IDL.Record({
  'id' : IDL.Text,
  'arrivalTime' : Time,
  'departureTime' : Time,
  'routeId' : IDL.Text,
  'busId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, BusStatus],
      [],
      [],
    ),
  'addBusTiming' : IDL.Func([IDL.Text, IDL.Text, Time, Time, IDL.Text], [], []),
  'addRoute' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'bookTicket' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PaymentMethod,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'getAllBuses' : IDL.Func([], [IDL.Vec(Bus)], ['query']),
  'getAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'getBusDetails' : IDL.Func([IDL.Text], [Bus], ['query']),
  'getBusesByRouteId' : IDL.Func([IDL.Text], [IDL.Vec(Bus)], ['query']),
  'getTicket' : IDL.Func([IDL.Text], [Ticket], ['query']),
  'getTimingsByRouteId' : IDL.Func([IDL.Text], [IDL.Vec(BusTiming)], ['query']),
  'updateBusPosition' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusStatus = IDL.Variant({
    'OnTime' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Delayed' : IDL.Null,
  });
  const Time = IDL.Int;
  const PaymentMethod = IDL.Variant({ 'Cash' : IDL.Null, 'Online' : IDL.Null });
  const Bus = IDL.Record({
    'id' : IDL.Text,
    'status' : BusStatus,
    'driverID' : IDL.Text,
    'busType' : IDL.Text,
    'busNumber' : IDL.Text,
    'speed' : IDL.Float64,
    'routeId' : IDL.Text,
    'currentStopIndex' : IDL.Nat,
    'conductorID' : IDL.Text,
  });
  const Route = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'toStop' : IDL.Text,
    'stops' : IDL.Vec(IDL.Text),
    'fromStop' : IDL.Text,
  });
  const Ticket = IDL.Record({
    'id' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Time,
    'timingId' : IDL.Text,
    'ticketId' : IDL.Text,
    'passengerName' : IDL.Text,
    'toStop' : IDL.Text,
    'fromStop' : IDL.Text,
    'busId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const BusTiming = IDL.Record({
    'id' : IDL.Text,
    'arrivalTime' : Time,
    'departureTime' : Time,
    'routeId' : IDL.Text,
    'busId' : IDL.Text,
  });
  
  return IDL.Service({
    'addBus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, BusStatus],
        [],
        [],
      ),
    'addBusTiming' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time, IDL.Text],
        [],
        [],
      ),
    'addRoute' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'bookTicket' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PaymentMethod,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'getAllBuses' : IDL.Func([], [IDL.Vec(Bus)], ['query']),
    'getAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'getBusDetails' : IDL.Func([IDL.Text], [Bus], ['query']),
    'getBusesByRouteId' : IDL.Func([IDL.Text], [IDL.Vec(Bus)], ['query']),
    'getTicket' : IDL.Func([IDL.Text], [Ticket], ['query']),
    'getTimingsByRouteId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BusTiming)],
        ['query'],
      ),
    'updateBusPosition' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };