/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Bus {
    id: string;
    status: BusStatus;
    driverID: string;
    busType: string;
    busNumber: string;
    speed: number;
    routeId: string;
    currentStopIndex: bigint;
    conductorID: string;
}
export interface Ticket {
    id: string;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    timingId: string;
    ticketId: string;
    passengerName: string;
    toStop: string;
    fromStop: string;
    busId: string;
    amount: bigint;
}
export interface BusTiming {
    id: string;
    arrivalTime: Time;
    departureTime: Time;
    routeId: string;
    busId: string;
}
export interface Route {
    id: string;
    name: string;
    toStop: string;
    stops: Array<string>;
    fromStop: string;
}
export enum BusStatus {
    OnTime = "OnTime",
    Cancelled = "Cancelled",
    Delayed = "Delayed"
}
export enum PaymentMethod {
    Cash = "Cash",
    Online = "Online"
}
export interface backendInterface {
    addBus(id: string, busNumber: string, driverID: string, conductorID: string, busType: string, routeId: string, status: BusStatus): Promise<void>;
    addBusTiming(id: string, busId: string, departureTime: Time, arrivalTime: Time, routeId: string): Promise<void>;
    addRoute(id: string, name: string, fromStop: string, toStop: string, stops: Array<string>): Promise<void>;
    bookTicket(id: string, ticketId: string, passengerName: string, fromStop: string, toStop: string, busId: string, timingId: string, paymentMethod: PaymentMethod, amount: bigint): Promise<void>;
    getAllBuses(): Promise<Array<Bus>>;
    getAllRoutes(): Promise<Array<Route>>;
    getBusDetails(busId: string): Promise<Bus>;
    getBusesByRouteId(routeId: string): Promise<Array<Bus>>;
    getTicket(ticketId: string): Promise<Ticket>;
    getTimingsByRouteId(routeId: string): Promise<Array<BusTiming>>;
    updateBusPosition(busId: string, currentStopIndex: bigint): Promise<void>;
}
import type { Bus as _Bus, BusStatus as _BusStatus, PaymentMethod as _PaymentMethod, Ticket as _Ticket, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBus(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: BusStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBus(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_BusStatus_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBus(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_BusStatus_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addBusTiming(arg0: string, arg1: string, arg2: Time, arg3: Time, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBusTiming(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBusTiming(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addRoute(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoute(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoute(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async bookTicket(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: PaymentMethod, arg8: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookTicket(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_PaymentMethod_n3(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookTicket(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_PaymentMethod_n3(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async getAllBuses(): Promise<Array<Bus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBuses();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBuses();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRoutes(): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoutes();
            return result;
        }
    }
    async getBusDetails(arg0: string): Promise<Bus> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusDetails(arg0);
                return from_candid_Bus_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusDetails(arg0);
            return from_candid_Bus_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusesByRouteId(arg0: string): Promise<Array<Bus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusesByRouteId(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusesByRouteId(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicket(arg0: string): Promise<Ticket> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicket(arg0);
                return from_candid_Ticket_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicket(arg0);
            return from_candid_Ticket_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimingsByRouteId(arg0: string): Promise<Array<BusTiming>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimingsByRouteId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimingsByRouteId(arg0);
            return result;
        }
    }
    async updateBusPosition(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusPosition(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BusStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusStatus): BusStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Bus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bus): Bus {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentMethod: _PaymentMethod;
    createdAt: _Time;
    timingId: string;
    ticketId: string;
    passengerName: string;
    toStop: string;
    fromStop: string;
    busId: string;
    amount: bigint;
}): {
    id: string;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    timingId: string;
    ticketId: string;
    passengerName: string;
    toStop: string;
    fromStop: string;
    busId: string;
    amount: bigint;
} {
    return {
        id: value.id,
        paymentMethod: from_candid_PaymentMethod_n12(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        timingId: value.timingId,
        ticketId: value.ticketId,
        passengerName: value.passengerName,
        toStop: value.toStop,
        fromStop: value.fromStop,
        busId: value.busId,
        amount: value.amount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BusStatus;
    driverID: string;
    busType: string;
    busNumber: string;
    speed: number;
    routeId: string;
    currentStopIndex: bigint;
    conductorID: string;
}): {
    id: string;
    status: BusStatus;
    driverID: string;
    busType: string;
    busNumber: string;
    speed: number;
    routeId: string;
    currentStopIndex: bigint;
    conductorID: string;
} {
    return {
        id: value.id,
        status: from_candid_BusStatus_n8(_uploadFile, _downloadFile, value.status),
        driverID: value.driverID,
        busType: value.busType,
        busNumber: value.busNumber,
        speed: value.speed,
        routeId: value.routeId,
        currentStopIndex: value.currentStopIndex,
        conductorID: value.conductorID
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Cash: null;
} | {
    Online: null;
}): PaymentMethod {
    return "Cash" in value ? PaymentMethod.Cash : "Online" in value ? PaymentMethod.Online : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnTime: null;
} | {
    Cancelled: null;
} | {
    Delayed: null;
}): BusStatus {
    return "OnTime" in value ? BusStatus.OnTime : "Cancelled" in value ? BusStatus.Cancelled : "Delayed" in value ? BusStatus.Delayed : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bus>): Array<Bus> {
    return value.map((x)=>from_candid_Bus_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BusStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusStatus): _BusStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusStatus): {
    OnTime: null;
} | {
    Cancelled: null;
} | {
    Delayed: null;
} {
    return value == BusStatus.OnTime ? {
        OnTime: null
    } : value == BusStatus.Cancelled ? {
        Cancelled: null
    } : value == BusStatus.Delayed ? {
        Delayed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    Cash: null;
} | {
    Online: null;
} {
    return value == PaymentMethod.Cash ? {
        Cash: null
    } : value == PaymentMethod.Online ? {
        Online: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
